name: Linux Clang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Linux Clang
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build
      run: cmake --build build -j

    - name: Run examples and tests
      run: ./build/DeviceParamsApp
